apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "keepalived-vip.fullname" . }}
  labels:
    app: {{ template "keepalived-vip.name" . }}
    chart: {{ template "keepalived-vip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }} # required
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "keepalived-vip.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "keepalived-vip.fullname" . }}
    namespace: {{ .Release.Namespace }} # required
