apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "keepalived-vip.fullname" . }}
  labels:
    app: {{ template "keepalived-vip.name" . }}
    chart: {{ template "keepalived-vip.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
