apiVersion: v1
kind: Service
metadata:
  name: {{ template "nfs-provisioner.fullname" . }}
  labels:
    app: {{ template "nfs-provisioner.name" . }}
    chart: {{ template "nfs-provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      protocol: TCP
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: {{ template "nfs-provisioner.name" . }}
    release: {{ .Release.Name }}
