kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nfs-provisioner.fullname" . }}
  labels:
    app: {{ template "nfs-provisioner.name" . }}
    chart: {{ template "nfs-provisioner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }} # required
subjects:
  - kind: ServiceAccount
    name: {{ template "nfs-provisioner.fullname" . }}
    namespace: {{ .Release.Namespace }} # required
roleRef:
  kind: ClusterRole
  name: {{ template "nfs-provisioner.fullname" . }} 
  apiGroup: rbac.authorization.k8s.io
